rate:           30
tolerance:      0.015
linear_vel:     0.1
angular_vel:    0.7
take_output:    true
initial_angle:  -90
input_file:     /home/adit/unicycle-model-patterns/src/turtlebot3_follower/path/pattern/waypoints_non_intersecting.txt
output_file:    /home/adit/unicycle-model-patterns/src/analysis/pattern/non_intersecting.txt